name = "MaxLFSR"
uuid = "baf6eaea-5535-433e-9234-5dfb57c28f99"
authors = ["Mark Hildebrand <mhildebrand@ucdavis.edu>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Random"]
